オブジェクト指向版lsコマンド
goruchanchan/ruby-practices pull request #16
Opened 2022-11-29 13:59 UTC by goruchanchan

ご確認よろしくお願いします🙇‍♂️

2022-12-05 03:40 UTC, u1tnk requested changes
全ての行まで見きれていないですが、基本的な部分とメソッド構成に指摘があったのでいったんここまでで見なおしてみてください。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +  attr_reader :error_list, :option_hash_list, :file_list, :directory_list
ruby(少なくともrails界隈)では配列は _listではなく複数形となります。
_hashもあまり使わないので私だったら optionsとかにしちゃいますね。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +    opt.on('-a') { |v| @option_hash_list[:a] = v }
オプション関係がこのクラスにまとまってるのは良いんですが、このハッシュに結果を全部入れて、参照するときもこのハッシュを使うのであればもったいないというかオブジェクト指向では無いと思います。
InputData内での持ち方は自由ですが、使う方はInputDataのインスタンスを参照して、 `input_data.option_all?`のほうにInputDataの内部構造とは関係無く分かりやすく参照できる必要があります。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +  def initialize
好みの世界でだいぶ細かいので参考までで修正不要ですが、ARGVはメイン処理から initializeの引数で渡して、各クラスでは参照しない方が各クラスの入力と出力がはっきりして分かりやすくなると思ってます。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +  def argv_parsing
argument_parsingと argv_parsingでは何が違うのかメソッド名では読み取れないので推測できるような名前にしましょう。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +        @error_list.push(path)
ここに来る例って何がありますか？
とりあえずあるとしてもプラクティスのレベルでは単に無視するとかで十分ですよ。
対応するのは良いんですが、 error_listとした場合、強制修了する必要があるものか、エラーメッセージは出すが処理は継続するものなのか…とかも適切に処理しないといけないので、最終的に追加するにしても正常系の整理がうまくいくまでは一旦削除した方がすすめやすいと思います。

2022-12-05 03:40 UTC, u1tnk commented on 08.ls_object/lib/formatter.rb
> +  def self.convert_array(lists)
全てのメソッドが クラスメソッドになっています。
業務一般でNGでは無いのですが、このプラクティスはオブジェクト指向へのリファクタリングが目的なのでNGです。
Formatterという名前であれば initializeで必要な情報をもらって、文字列を出力するインスタンスメソッドを用意しましょう。

2022-12-05 13:40 UTC, goruchanchan commented on 08.ls_object/bin/bin_ls.rb
> +ENV['POSIXLY_CORRECT'] = '1'
ls コマンドの仕様として、`ls [オプション] [パス]`という形でしたので、オプションは２番目の位置の時だけ実行した方がいいかと思いつけておりました😅

 ![image.png](https://www.evernote.com/l/AZD0nV82svdFRY18LwKSJ73LezfeiXzPJhAB/image.png)

2022-12-05 13:49 UTC, goruchanchan commented on 08.ls_object/bin/bin_ls.rb
> +puts LsFile.file_error(input_data.error_list) unless input_data.error_list.empty?
ls コマンドの仕様として存在しないパスが入力された場合、最初にエラーをまとめて表示するようでしたので、このようにしておりました🙇‍♂️

![image.png](https://www.evernote.com/l/AZDqkfkxTSdKLq3itzV6d1rnRPcxcX9MztgB/image.png)

ご指摘の通り、プラクティス的には不要なのと、本家を完全には再現できていないので無くそうと思います！

2022-12-05 13:59 UTC, goruchanchan commented on 08.ls_object/bin/bin_ls.rb
> +  puts unless input_data.error_list.empty?
エラー一覧がある場合、ファイル一覧との間に改行が入っていると勘違いしておりました、、、
![image.png](https://www.evernote.com/l/AZD2GcpSr_1Gj7QdgoQO6nwKV2V07LPXWPgB/image.png)

不要ですので、削除しておきます！

2022-12-05 14:24 UTC, goruchanchan commented on 08.ls_object/lib/input_data.rb
> +        @error_list.push(path)
おっしゃる通りだと思いました！まずは正常系をしっかりと作ろうと思います！

2022-12-08 15:59 UTC, u1tnk requested changes
細かいところも色々書いてますが、一番大きいのはmoduleをincludeしているところですね。
includeは有効なシーンもあるのですが、オブジェクト指向の大事な機能では無いのでこのプラクティスでは使わない方が良いです。

2022-12-08 15:59 UTC, u1tnk commented on 08.ls_object/bin/bin_ls.rb
> +ENV['POSIXLY_CORRECT'] = '1'
なるほど。
プラクティスとしては仕様的にどっちでも大丈夫です 🙆‍♀️ 
この部分も無くても良いですがあっても問題ありません 🙆‍♀️

2022-12-08 15:59 UTC, u1tnk commented on 08.ls_object/bin/bin_ls.rb
> +options = {}
オプションの処理はInputDataのままでも良かったですが、ここでも大丈夫です 🙆‍♀️ ほぼ定型文ですし、
ただ、ファイルの処理の方は directory/fileの順番 `.`の処理などちょっと複雑なので InputDataなどクラス内にあって欲しいですね。

メイン処理全体の流れがざっと見て分かるのが大事なので、にあるのは定型的な処理簡単な分岐、受け渡しぐらいにしましょう。

なので最大文字数の更新などもどこかのクラスに移動しましょう。

2022-12-08 15:59 UTC, u1tnk commented on 08.ls_object/lib/input_data.rb
> +              :options
optionsは今使ってなさそうですね。

2022-12-08 15:59 UTC, u1tnk commented on 08.ls_object/lib/ls_directory.rb
> +  include Formatter
moduleのincludeは LsDirectoryとLsFileの重複を減らすことはできますが、結局のところメソッドをファイル分割したのと本質的に変わっていません。
オブジェクト指向の良いところは機能ごとのクラスに分割して独立性を高めて互いに依存を減らすことで、それぞれを独立して開発しやすくするところです。
現状の構成だと LsDirectoryが呼んでいるメソッドがどこにあるのか複数ファイルを見ないと分かりませんし、それぞれでインスタンス変数も参照可能でscopeが広くなってしまって依存度は高い状態です。
Formatterは現在インスタンス変数を使っていないから依存度は高くないのでは？と思われるかもしれませんが、見えるのであれば使っていないか確認する必要があるので見えない(オブジェクト指向で言うカプセル化)とは別物です。
現在メソッドごとの引数と返り値のみで受け渡しをしているので、元のクラスメソッドと変わらないです。
インスタンス化して最低限のメソッドを使ってやりとりできると良いですね。

2022-12-15 16:31 UTC, u1tnk requested changes
だいぶ良くなりました 👍 

ただ、クラス構成的にFormatterが大き過ぎるようですね。
内容を見ていくと、大きく二つの処理があるように思います。

- 出力用に整理、整形、変換する。
- ファイル情報を取得する。(stat関連とかpermitとか)

に分けられると思います。
前者はまさしくフォーマットなので、後者を分離して欲しいです。
fileを表すクラスを作ってFileGroupのfilesに持たせて利用すると良いと思います。

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/bin/bin_ls.rb
> +input = Input.new(paths: ARGV, option_all: options[:all], option_reverse: options[:reverse])
スッキリしましたね 👍

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/lib/file_group.rb
> +  def initialize(title:, files:)
全然これで良いんですが、このぐらいの情報量でメソッドも無ければhashとか Structとか使っても良いですね。(後者はちょっとマニアックです)

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/lib/input.rb
> +  def parse_option(path:)
parse_optionはoptparseがありますし、慣習的に alrなどのオプションを取得するときに使われる名前なので誤解を招きますね。
また、この二行は別のことをやっているのでメソッド化するなら分けるべきです。

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/lib/input.rb
> +  def classfy_type
タイプによって分類するという意図でしょうか？

メソッド名は 動詞→目的語になるのがよくあるパターンなので、この単語だと `clsasfy_paths`とかtypeを使いたいなら`classfy_by_type`とかの方が自然な気はします。
また、プログラミングでclassは特別な意図を連想してしまってあまりよく無いですね。 
整理する分類するなどで別の単語を探してみてください。

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/lib/input.rb
> +    @paths = paths.empty? ? ['.'] : paths
細かいのですが、 initializeで単純に保存して classfy_typeで色々ロジックを書いてるかと思いきや、この部分もロジックが入っていて、ちょっと一貫性が足りないと思いました。

2022-12-15 16:31 UTC, u1tnk commented on 08.ls_object/lib/formatter.rb
> +    long_info = File.lstat(full_path) # statだとシンボリックリンクのパスが元ファイルになってしまうので、lstat
右辺の内容からすると変数名に付くのは infoでは無くstatの方が分かりやすいかと思います。

2022-12-18 13:39 UTC, goruchanchan commented on 08.ls_object/lib/file_group.rb
> +  def initialize(title:, files:)
一旦Structを使って実装したのですが、トータルブロックサイズ計算をやらせるならこのクラスかと思い、再度復活させました🤔

2022-12-18 15:06 UTC, u1tnk requested changes
指摘しましたが、もう全体の構成については無くなったのでもうちょっとです！ 💪

2022-12-19 07:17 UTC, goruchanchan commented on 08.ls_object/lib/file_detail.rb
> +    @attribute = analyze_attribure
ご指摘のとおり、『lオプションなくてもデータ保持してしまうの微妙🧐』と思ってましたが案も見つからずそのままでした😅

**遅延処理**　非常に勉強なりました🙇‍♂️

2022-12-19 16:34 UTC, u1tnk approved these changes

2022-12-20 12:41 UTC, merged